### ISSUE TITLE
Music commands need more feedback

### ISSUE THREAD

**Issue by morgaesis** [michael-je/the-lone-dancer#10]
- [x]  `!play`, `!stop`, `!pause`, `!resume`, and `!skip` should be "reacted" to. Bot should reply in pretty colors to commands asking for information
- [ ] #30
- [x]  Bot should write the name of the song when it starts playing
- [x]  Let user know they are not in a voice channel

**Comment by michael-je** [comment]
Issue is now resolved by multiple past commits.

**Comment by morgaesis** [comment]
@michael-je Should this be closed? Not all points are fixed:
- Commands aren't reacted to (with an emoji)
- Not all commands are pretty-formatted
- New linked issue is not yet fixed (#30)

**Comment by michael-je** [comment]
Yes, I think it should:

- In my opinion not _all_ commands need to be reacted to, since some of them already provide feedback via text messages.
- Not sure what you mean with the second point.
- The new linked issue isn't fixed but I don't feel like it's elevant to this one. I checked the box to show completeness, but issue #30 is still open.

**Comment by morgaesis** [comment]
Sorry, hadn't noticed some of the recent reaction changes. I think this issue should still be open as a meta-issue tracking all feedback-related issues. Currently there is only one, so it's kinda silly, but I might add more if I think of some convoluted edge case.

**Comment by michael-je** [comment]
I see your point but I just have to disagree. All sub-tasks of this issue have been addressed. 
If you want to add anything else related to feedback then you can open a new, self-contained issue.

**Comment by michael-je** [comment]
Sorry, I accidentally wiped the first task while trying to create a new issue, maybe you could change it back to:
`!play`, `!stop`, `!pause`, `!resume`, and `!skip` should be "reacted" to.
