### ISSUE TITLE
Bot is blocked while fetching playlist data

### ISSUE THREAD

**Issue by michael-je** [michael-je/the-lone-dancer#60]
Bot should be non-blocking and able to handle new commands while fetching playlist data. 

As it stands, new commands will only be handled after an added playlist has finished processing. This becomes especially bad if the playlist being added is long, in which case the bot can be blocked for a very long time.

Related to #59, but I don't think this is the same issue.

**Comment by morgaesis** [comment]
I'm trying to solve this in #65.

I'm thinking... Do we really need locks?
@gardarandri, the blame for locks goes to you; why locking?

Writing down my ideas and marking "done" things I think are NBD or are inconvenient/strange regardless of the lock:
- [x] The media queue is thread-safe, so no loss of data there.
- [x] Any combination of two users calling `-next`, `-skip`, `-play song`, `-pause`, `-stop`, `-resume`. Likely results in a conversation like "Wow, we both made a command at the same time...". No expected side-effects other than the users might have to do the command again. Strange, unlikely, low impact.
- [x] *A* uses `-play some playlist`, *B* uses `-next`, causing next song in playlist to play. Subsequent `-next` while still fetching playlist will play not-yet-published playlist songs. Meanwhile playlist loading is being displayed, so *B* knows a playlist is being fetched. Strange, moderately unlikely, low impact.
- [ ] *A* uses `-play some playlist`, *B* uses `-clear`, here we have a race condition. If the `-clear` empties the queue at some point while playlist is still fetching, `-clear` will finish, but playlist fetching will continue until completion. Calling `-clear` again after playlist loading completes drops the rest of the playlist. Could be frequent if users try to cancel playlist loading. Moderately likely, at most annoying.
